-- MySQL Script generated by MySQL Workbench
-- Sat Oct 28 20:26:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plutucart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plutucart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plutucart` DEFAULT CHARACTER SET utf8 ;
USE `plutucart` ;

-- -----------------------------------------------------
-- Table `plutucart`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutucart`.`account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `imie` VARCHAR(15) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL,
  `account_role` ENUM('guest', 'customer') NOT NULL,
  PRIMARY KEY (`id_account`),
  UNIQUE INDEX `email_google_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutucart`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutucart`.`wallet` (
  `id_wallet` INT NOT NULL AUTO_INCREMENT,
  `name_wallet` VARCHAR(45) NOT NULL,
  `balance_wallet` DECIMAL(13,2) NOT NULL,
  `account_id_account` INT NOT NULL,
  `create_walltet_on` DATETIME NOT NULL,
  `update_wallet_on` DATETIME NOT NULL,
  PRIMARY KEY (`id_wallet`),
  INDEX `fk_wallet_account1_idx` (`account_id_account` ASC) VISIBLE,
  CONSTRAINT `fk_wallet_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `plutucart`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutucart`.`goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutucart`.`goal` (
  `id_goal` INT NOT NULL AUTO_INCREMENT,
  `name_goal` VARCHAR(45) NOT NULL,
  `amount_goal` DECIMAL(13,2) NOT NULL,
  `deficit` DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  `account_id_account` INT NOT NULL,
  `create_goal_on` DATETIME NOT NULL,
  `update_goal_on` DATETIME NOT NULL,
  PRIMARY KEY (`id_goal`),
  INDEX `fk_goal_account1_idx` (`account_id_account` ASC) VISIBLE,
  CONSTRAINT `fk_goal_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `plutucart`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutucart`.`transaction_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutucart`.`transaction_category` (
  `id_transaction_category` INT NOT NULL AUTO_INCREMENT,
  `name_transaction_category` VARCHAR(45) NOT NULL,
  `type_category` ENUM('income', 'expense') NOT NULL,
  PRIMARY KEY (`id_transaction_category`),
  UNIQUE INDEX `name_transaction_category_UNIQUE` (`name_transaction_category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutucart`.`debt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutucart`.`debt` (
  `id_debt` INT NOT NULL AUTO_INCREMENT,
  `name_debt` VARCHAR(45) NOT NULL,
  `amount_debt` DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  `installment_debt` INT NOT NULL DEFAULT 1,
  `num_of_installment_pay` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `create_debt_on` DATETIME NOT NULL,
  `update_debt_on` DATETIME NOT NULL,
  `account_id_account` INT NOT NULL,
  PRIMARY KEY (`id_debt`),
  INDEX `fk_debt_account1_idx` (`account_id_account` ASC) VISIBLE,
  CONSTRAINT `fk_debt_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `plutucart`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutucart`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutucart`.`transaction` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `stm_transaction` DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  `statement_type` ENUM('income', 'expense') NOT NULL,
  `date_transaction` DATETIME NOT NULL,
  `tran_category_id_category` INT NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `image_url` VARCHAR(100) NULL DEFAULT NULL,
  `debt_id_debt` INT NULL,
  `goal_id_goal` INT NULL,
  `create_transaction_on` DATETIME NOT NULL,
  `update_transaction_on` DATETIME NOT NULL,
  `wallet_id_wallet` INT NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_transaction_debt1_idx` (`debt_id_debt` ASC) VISIBLE,
  INDEX `fk_transaction_category1_idx` (`tran_category_id_category` ASC) VISIBLE,
  INDEX `fk_transaction_goal1_idx` (`goal_id_goal` ASC) VISIBLE,
  INDEX `fk_transaction_wallet1_idx` (`wallet_id_wallet` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_debt1`
    FOREIGN KEY (`debt_id_debt`)
    REFERENCES `plutucart`.`debt` (`id_debt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_category1`
    FOREIGN KEY (`tran_category_id_category`)
    REFERENCES `plutucart`.`transaction_category` (`id_transaction_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_goal1`
    FOREIGN KEY (`goal_id_goal`)
    REFERENCES `plutucart`.`goal` (`id_goal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_wallet1`
    FOREIGN KEY (`wallet_id_wallet`)
    REFERENCES `plutucart`.`wallet` (`id_wallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert into transaction_category values(1 , 'Food' , 2);
insert into transaction_category values(2 , 'Travel' , 2);
insert into transaction_category values(3 , 'Pocket money' , 1);
