-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 23:25:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plutocart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `plutocart` ;

-- -----------------------------------------------------
-- Schema plutocart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plutocart` DEFAULT CHARACTER SET utf8 ;
USE `plutocart` ;

-- -----------------------------------------------------
-- Table `plutocart`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutocart`.`account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `imei` VARCHAR(15) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL,
  `account_role` ENUM('guest', 'customer') NOT NULL,
  PRIMARY KEY (`id_account`),
  UNIQUE INDEX `email_google_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutocart`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutocart`.`wallet` (
  `id_wallet` INT NOT NULL AUTO_INCREMENT,
  `name_wallet` VARCHAR(45) NOT NULL,
  `balance_wallet` DECIMAL(13,2) NOT NULL,
  `account_id_account` INT NOT NULL,
  `create_wallet_on` DATETIME NOT NULL,
  `update_wallet_on` DATETIME NOT NULL,
  PRIMARY KEY (`id_wallet`),
  INDEX `fk_wallet_account1_idx` (`account_id_account` ASC) VISIBLE,
  CONSTRAINT `fk_wallet_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `plutocart`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutocart`.`goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutocart`.`goal` (
  `id_goal` INT NOT NULL AUTO_INCREMENT,
  `name_goal` VARCHAR(45) NOT NULL,
  `amount_goal` DECIMAL(13,2) NOT NULL,
  `deficit` DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  `account_id_account` INT NOT NULL,
  `create_goal_on` DATETIME NOT NULL,
  `update_goal_on` DATETIME NOT NULL,
  PRIMARY KEY (`id_goal`),
  INDEX `fk_goal_account1_idx` (`account_id_account` ASC) VISIBLE,
  CONSTRAINT `fk_goal_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `plutocart`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutocart`.`transaction_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutocart`.`transaction_category` (
  `id_transaction_category` INT NOT NULL AUTO_INCREMENT,
  `name_transaction_category` VARCHAR(45) NOT NULL,
  `type_category` ENUM('income', 'expense') NOT NULL,
  PRIMARY KEY (`id_transaction_category`),
  UNIQUE INDEX `name_transaction_category_UNIQUE` (`name_transaction_category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutocart`.`debt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutocart`.`debt` (
  `id_debt` INT NOT NULL AUTO_INCREMENT,
  `name_debt` VARCHAR(45) NOT NULL,
  `amount_debt` DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  `installment_debt` INT NOT NULL DEFAULT 1,
  `num_of_installment_pay` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `create_debt_on` DATETIME NOT NULL,
  `update_debt_on` DATETIME NOT NULL,
  `account_id_account` INT NOT NULL,
  PRIMARY KEY (`id_debt`),
  INDEX `fk_debt_account1_idx` (`account_id_account` ASC) VISIBLE,
  CONSTRAINT `fk_debt_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `plutocart`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plutocart`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plutocart`.`transaction` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `stm_transaction` DECIMAL(13,2) NOT NULL DEFAULT 0.00,
  `statement_type` ENUM('income', 'expense') NOT NULL,
  `date_transaction` DATETIME NOT NULL,
  `tran_category_id_category` INT NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `image_url` VARCHAR(100) NULL DEFAULT NULL,
  `debt_id_debt` INT NULL,
  `goal_id_goal` INT NULL,
  `create_transaction_on` DATETIME NOT NULL,
  `update_transaction_on` DATETIME NOT NULL,
  `wallet_id_wallet` INT NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_transaction_debt1_idx` (`debt_id_debt` ASC) VISIBLE,
  INDEX `fk_transaction_category1_idx` (`tran_category_id_category` ASC) VISIBLE,
  INDEX `fk_transaction_goal1_idx` (`goal_id_goal` ASC) VISIBLE,
  INDEX `fk_transaction_wallet1_idx` (`wallet_id_wallet` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_debt1`
    FOREIGN KEY (`debt_id_debt`)
    REFERENCES `plutocart`.`debt` (`id_debt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_category1`
    FOREIGN KEY (`tran_category_id_category`)
    REFERENCES `plutocart`.`transaction_category` (`id_transaction_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_goal1`
    FOREIGN KEY (`goal_id_goal`)
    REFERENCES `plutocart`.`goal` (`id_goal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_wallet1`
    FOREIGN KEY (`wallet_id_wallet`)
    REFERENCES `plutocart`.`wallet` (`id_wallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into account (id_account , user_name , imei , email , password , account_role) values(1 , 'admin' , 'admin_imei' , 'admin@gmail.com' , 'adminpassword' , 2);

insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(1 , 'Salary' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(2 , 'Pocket money' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(3 , 'Davidend' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(4 , 'Allowance' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(5 , 'Pension' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(6 , 'Reward' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(7 , 'Bonus' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(8 , 'Collect rent' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(9 , 'Win the lottery' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(10 , 'Freelance' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(11 , 'Part-time' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(12, 'Sell Things' , 1); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(13, 'Red envelope' , 1); 

insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(14 , 'Food' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(15, 'Gasoline' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(16, 'Telephone bill' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(17, 'Medical' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(18, 'Shopping' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(19, 'Electricity bill' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(20, 'Water bill' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(21, 'Home installment' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(22, 'Travel' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(23, 'Fare' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(24, 'Drinking' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(25, 'Donate' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(26, 'Household items' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(27, 'Pay for rent' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(28, 'Transfer money to others' , 2); 
insert into transaction_category (id_transaction_category , name_transaction_category , type_category) values(29, 'Lottery' , 2); 

insert into wallet (id_wallet , name_wallet , balance_wallet , status_wallet , account_id_account , create_wallet_on , update_wallet_on) values(1 , 'admin wallet' , 100000.00 , default , 1 , now() , now());
insert into wallet (id_wallet , name_wallet , balance_wallet , status_wallet , account_id_account , create_wallet_on , update_wallet_on) values(2 , 'admin wallet' , 999999.00 , default , 1 , now() , now());
